export default {
    products: [
        {
        _id:'1',
        name: 'full designer set',
        category: 'Interior Designs',
        image: '/images/product-1.jpg',
        price: '#'+222,
        brand: 'Hugo',
        width: 280,
        height: 220,
        rating: 5,
        numReviews: 15,
        countInStock:10,
         },
        {
        _id:'2',
         name: 'Books Contrast truth',
        category: 'Interior Designs',
        image: '/images/product-2.jpg',
        price: '#'+621,
        brand: 'Channel',
        width: 280,
        height: 220,
        rating: 3.5,
        numReviews: 5,
        countInStock: 3,
         },
        {
         _id:'3',
        name: 'slim feet shirt',
        category: 'Interior Designs',
        image: '/images/product-3.jpg',
        price: '#'+312,
        brand: 'M&S',
        width: 280,
        height: 220,
        rating: 4.5,
        numReviews: 12,
        countInStock: 7,
        },
        {
        _id:'4',
        name: 'Brown leather shoe',
        category: 'Interior Designs',
        image: '/images/product-4.jpg',
        price: '#'+250,
        brand: 'Nike',
        width: 280,
        height: 220,
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
        },
        {
        _id:'5',
        name: 'designer jean pant',
        category: 'Interior Designs',
        image: '/images/product-5.jpg',
        price: '#'+300,
        brand: 'Boss',
        width: 280,
        height:220,
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
        },
        {
        _id:'6',
        name: 'Rolex watch',
        category: 'Interior Designs',
        image: '/images/product-6.jpg',
        price: '#'+590,
        brand: 'Home Made',
        width: 280,
        height: 220,
        rating: 4.5,
        numReviews: 13,
        countInStock: 5,
        },
    ],
};